version: "3.8"
volumes:
  postgres:
services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
